name:         Encontro de estudos em Pierre Bourdieu
description:  PÃ¡gina do encontro de estudos em Pierre Bourdieu
title:        Encontro de estudos em Pierre Bourdieu
date:         12 a 14 de novembro de 2014
author:
  name:       Grupo de Estudos em Bourdieu 
  # email:      forum.ppgs.unicamp@gmail.com
# brand:        Encontro de Estudos em Pierre Bourdieu
permalink:    pretty
markdown:     kramdown
exclude:      ['.rvmrc', '.rbenv-version', 'README.md', 'Rakefile', 'changelog.md']
highlighter:  pygments
# During production, we better set the url to localhost:
url:          http://localhost:4000
